### PR TITLE
Added dark mode 

### PR DESCRIPTION
**Pull request by AwsmAsim**
For Hacktoberfest 2021
Added icon at the top right corner and added dark mode (GIF Attached).
Changes done in: 
- pubspec,yaml (added provider and shared_preferences)
- homepage.screens.dart
- added controller
1stHacktoberfest - Google Chrome 2021-10-15 20-51-53

### CODE REVIEW

**Comment by viveeeeeek** [comment]
Even if we switch to dark theme it is only applicable for homepage only.
Can you please implement it for detailed screen too?
let me know I'll create new issue for it.

Thank you.

**Comment by AwsmAsim** [comment]
Yeah, we can do that with the text. But since we are using a background image, there we have to use the Consumer every time. 
Shall we implement this with the text color ?

**Comment by viveeeeeek** [comment]
not with the text but on detail page
image
here

**Comment by AwsmAsim** [comment]
Yeah we can

**Pull request merged**
